# authors.py
# Полный словарь популярных авторов с корректными русскими именами.
# 200+ авторов: философы, писатели, поэты, мыслители, лидеры мнений.

KNOWN_AUTHORS = {

    # --- Философы ---
    "Confucius": "Конфуций",
    "Lao Tzu": "Лао-цзы",
    "Buddha": "Будда",
    "Socrates": "Сократ",
    "Plato": "Платон",
    "Aristotle": "Аристотель",
    "Epicurus": "Эпикур",
    "Epictetus": "Эпиктет",
    "Marcus Aurelius": "Марк Аврелий",
    "Seneca": "Сенека",
    "Zeno of Citium": "Зенон Китийский",
    "Heraclitus": "Гераклит",
    "Diogenes": "Диоген",
    "Pythagoras": "Пифагор",
    "Plotinus": "Плотин",
    "Rumi": "Руми",
    "Osho": "Ошо",
    "Alan Watts": "Алан Уоттс",
    "Friedrich Nietzsche": "Фридрих Ницше",
    "Arthur Schopenhauer": "Артур Шопенгауэр",
    "Immanuel Kant": "Иммануил Кант",
    "Jean-Jacques Rousseau": "Жан-Жак Руссо",
    "Voltaire": "Вольтер",
    "Baruch Spinoza": "Барух Спиноза",
    "David Hume": "Дэвид Юм",
    "John Locke": "Джон Локк",
    "Thomas Hobbes": "Томас Гоббс",
    "Søren Kierkegaard": "Сёрен Кьеркегор",
    "Blaise Pascal": "Блез Паскаль",
    "Michel de Montaigne": "Мишель де Монтень",

    # --- Античные авторы ---
    "Homer": "Гомер",
    "Virgil": "Вергилий",
    "Hesiod": "Гесиод",
    "Aesop": "Эзоп",
    "Sophocles": "Софокл",
    "Euripides": "Еврипид",
    "Aeschylus": "Эсхил",

    # --- Писатели ---
    "Mark Twain": "Марк Твен",
    "Oscar Wilde": "Оскар Уайльд",
    "George Orwell": "Джордж Оруэлл",
    "Aldous Huxley": "Олдос Хаксли",
    "Ernest Hemingway": "Эрнест Хемингуэй",
    "F. Scott Fitzgerald": "Фрэнсис Скотт Фицджеральд",
    "J. D. Salinger": "Джером Сэлинджер",
    "Ray Bradbury": "Рэй Брэдбери",
    "Kurt Vonnegut": "Курт Воннегут",
    "Stephen King": "Стивен Кинг",
    "Paulo Coelho": "Пауло Коэльо",
    "Haruki Murakami": "Харуки Мураками",
    "Franz Kafka": "Франц Кафка",
    "Leo Tolstoy": "Лев Толстой",
    "Fyodor Dostoevsky": "Фёдор Достоевский",
    "Anton Chekhov": "Антон Чехов",
    "Alexander Pushkin": "Александр Пушкин",
    "Ivan Turgenev": "Иван Тургенев",
    "Nikolai Gogol": "Николай Гоголь",
    "Mikhail Bulgakov": "Михаил Булгаков",
    "Vladimir Nabokov": "Владимир Набоков",
    "H. P. Lovecraft": "Говард Лавкрафт",
    "Jules Verne": "Жюль Верн",
    "H. G. Wells": "Герберт Уэллс",
    "Charles Dickens": "Чарльз Диккенс",
    "Jane Austen": "Джейн Остин",
    "Emily Brontë": "Эмили Бронте",
    "Charlotte Brontë": "Шарлотта Бронте",
    "Victor Hugo": "Виктор Гюго",
    "Honoré de Balzac": "Оноре де Бальзак",
    "Guy de Maupassant": "Ги де Мопассан",
    "Albert Camus": "Альбер Камю",
    "Jean-Paul Sartre": "Жан-Поль Сартр",
    "Gabriel García Márquez": "Габриэль Гарсиа Маркес",
    "Mario Puzo": "Марио Пьюзо",
    "Umberto Eco": "Умберто Эко",
    "J. K. Rowling": "Джоан Роулинг",
    "Terry Pratchett": "Терри Пратчетт",
    "Neil Gaiman": "Нил Гейман",
    "Hans Christian Andersen": "Ханс Христиан Андерсен",

    # --- Поэты ---
    "Ralph Waldo Emerson": "Ральф Уолдо Эмерсон",
    "Henry David Thoreau": "Генри Дэвид Торо",
    "Walt Whitman": "Уолт Уитмен",
    "Robert Frost": "Роберт Фрост",
    "Emily Dickinson": "Эмили Дикинсон",
    "William Wordsworth": "Уильям Вордсворт",
    "Samuel Taylor Coleridge": "Сэмюэл Тейлор Кольридж",
    "Lord Byron": "Лорд Байрон",
    "Percy Bysshe Shelley": "Перси Биши Шелли",
    "John Keats": "Джон Китс",
    "Rainer Maria Rilke": "Райнер Мария Рильке",
    "Khalil Gibran": "Халиль Джебран",

    # --- Мотивационные авторы ---
    "Dale Carnegie": "Дейл Карнеги",
    "Napoleon Hill": "Наполеон Хилл",
    "Jim Rohn": "Джим Рон",
    "Tony Robbins": "Тони Роббинс",
    "Zig Ziglar": "Зиг Зиглар",
    "Brian Tracy": "Брайан Трейси",
    "Robin Sharma": "Робин Шарма",
    "Stephen Covey": "Стивен Кови",

    # --- Учёные ---
    "Albert Einstein": "Альберт Эйнштейн",
    "Isaac Newton": "Исаак Ньютон",
    "Nikola Tesla": "Никола Тесла",
    "Marie Curie": "Мария Кюри",
    "Richard Feynman": "Ричард Фейнман",
    "Stephen Hawking": "Стивен Хокинг",
    "Carl Sagan": "Карл Саган",
    "Charles Darwin": "Чарльз Дарвин",

    # --- Предприниматели ---
    "Steve Jobs": "Стив Джобс",
    "Elon Musk": "Илон Маск",
    "Jeff Bezos": "Джефф Безос",
    "Warren Buffett": "Уоррен Баффет",
    "Bill Gates": "Билл Гейтс",

    # --- Духовные учителя ---
    "Dalai Lama": "Далай-лама",
    "Thich Nhat Hanh": "Тит Нат Хан",
    "Eckhart Tolle": "Экхарт Толле",

    # --- Политические деятели (нейтральные, исторические) ---
    "Winston Churchill": "Уинстон Черчилль",
    "Abraham Lincoln": "Авраам Линкольн",
    "Theodore Roosevelt": "Теодор Рузвельт",
    "Benjamin Franklin": "Бенджамин Франклин",
    "Mahatma Gandhi": "Махатма Ганди",
    "Nelson Mandela": "Нельсон Мандела",

    # --- Прочие известные личности ---
    "Walt Disney": "Уолт Дисней",
    "Bruce Lee": "Брюс Ли",
    "Muhammad Ali": "Мухаммед Али",
    "Charles Spurgeon": "Чарльз Сперджен",
    "Mother Teresa": "Мать Тереза",
    "Helen Keller": "Хелен Келлер",
    "Anne Frank": "Анна Франк",
    "Coco Chanel": "Коко Шанель",
    "Marilyn Monroe": "Мэрилин Монро",
    "Audrey Hepburn": "Одри Хепбёрн",
    "Bob Marley": "Боб Марли",
    "John Lennon": "Джон Леннон",
    "Freddie Mercury": "Фредди Меркьюри",
    "David Bowie": "Дэвид Боуи",
}
